### ISSUE TITLE
Wrong folder name given during vendor:publish

### ISSUE THREAD

**Issue by mfashraf** [socieboy/alerts#1]
Hi, during my installation on a Centos 7 server, I got this error:

Can't locate path: </var/www/laravel/vendor/socieboy/alerts/src/Libraries/sweetalert.css>
Can't locate path: </var/www/laravel/vendor/socieboy/alerts/src/Libraries/sweetalert.js>

Apparently, during composer update, the path created was libraries instead of Libraries (small letter L).

**Comment by socieboy** [comment]
You right! Thank you!
